/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_03_LPSPI1_SDI,0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_04_LPSPI1_SDO,0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_05_GPIOMUX_IO19,0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_06_LPSPI1_SCK,0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_09_FLEXIO1_IO01, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_10_FLEXIO1_IO02, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_11_FLEXIO1_IO03, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_12_FLEXIO1_IO04, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_13_FLEXIO1_IO05, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_00_FLEXIO1_IO06, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_01_FLEXIO1_IO07, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_02_FLEXIO1_IO08, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_03_FLEXIO1_IO09, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_04_FLEXIO1_IO10, 0U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_05_FLEXIO1_IO11, 0u);
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_13_GPIO2_IO13, 0u);
  IOMUXC_SetPinMux(IOMUXC_GPIO_06_GPIOMUX_IO06, 0u);
  IOMUXC_SetPinMux(IOMUXC_GPIO_07_GPIOMUX_IO07, 0u);
  IOMUXC_SetPinMux(IOMUXC_GPIO_08_GPIOMUX_IO08, 0u);
  
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_03_LPSPI1_SDI,0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_04_LPSPI1_SDO,0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_05_GPIOMUX_IO19,0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_06_LPSPI1_SCK,0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_09_FLEXIO1_IO01, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_10_FLEXIO1_IO02, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_11_FLEXIO1_IO03, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_12_FLEXIO1_IO04, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_13_FLEXIO1_IO05, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_00_FLEXIO1_IO06, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_01_FLEXIO1_IO07, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_02_FLEXIO1_IO08, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_03_FLEXIO1_IO09, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_04_FLEXIO1_IO10, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_05_FLEXIO1_IO11, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_13_GPIO2_IO13, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_06_GPIOMUX_IO06, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_07_GPIOMUX_IO07, 0x10A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_08_GPIOMUX_IO08, 0x10A0U);
}

void BOARD_Init_I2C_Pins(void) {
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_07_LPI2C2_SDA, 0u);
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_08_LPI2C2_SCL, 0u);

  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_07_LPI2C2_SDA, 0xD8A0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_08_LPI2C2_SCL, 0xD8A0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
